### ISSUE TITLE
where to buy just the LCD module ?

### ISSUE THREAD

**Issue by janjos0** [blurpy/transistor-tester#1]
Hi Christian,
First let me thank you for the detailed description of this specific model of this very popular component tester. It was a pleasure to read. And second I don't have an issue, just a question, please read further.

I have the same tester as you, but mine was bought at DealExtreme.
In fact I have two of them because the first one arrived with a broken LCD. When I asked for a LCD replacement, they just sent me a complete kit. Now I would like to replace the broken LCD but up to now and after searching the www for days I do not find a 100% replacement.

Do you or someone reading this, know a supplier for the LCD ?
Including of course the LCD mounting PCB with the 1117 VREG and CD4050 level translator.

Sorry to ask here but I also asked on the product page of DX and the answer I got was "for the price just buy a all new kit instead of replacing the LCD". I don't think that is really environment friendly if we just trow away stuff that can easily be repaired.
So if someone knows a supplier for the LCD please let me know. Thank you.

**Comment by blurpy** [comment]
Hi janjos0,

Thank you, glad to hear!

I agree that it's much better to find a screen replacement if possible. I do not know where to find that exact LCD. Perhaps you can find it somewhere on AliExpress? The firmware supports different kinds of screens, so perhaps another option would be to find another compatible one instead.

I think the eevblog forum would be your best bet in order to find a solution. Have you tried posting here? https://www.eevblog.com/forum/testgear/$20-lcr-esr-transistor-checker-project/

Good luck! If you find a solution, I'll be interested in hearing about it.

**Comment by janjos0** [comment]
Thanks for the tip.
In the meanwhile I searched that forum with words like LCD, broken, defect, ST7735, ... and did find some users with the same problem, but no solution.
I don't have an account at eevblog and from what I read I don't think I will create one.
I am afraid I will never find a drop-in replacement and will just keep it for replacement parts.
My best wishes to you.

**Comment by blurpy** [comment]
Ok, thanks for the update anyway!
